#ifndef __VALUES_H_GUARD__
#define __VALUES_H_GUARD__

#define CARGO_POINTER_FUNCTION_ERROR NULL
#define CARGO_INT_FUNCTION_ERROR -1
#define CARGO_KEY_ALREADY_EXISTS -2
#define CARGO_INT_FUNCTION_SUCCESS 0

#endif
